Select 
  id,
  name,
  orderindex,
  override_statuses,
  hidden,
  space,
  task_count,
  archived,
  statuses,
  lists,
  permission_level,
  space_id
Select 
  Id,
  Pozitive_numbers,
  Decimal_numbers,
  Negative,
  Negative_double,
  Text,
  Id_repeatable,
  Id_text_repeatable_,
  Id_of_mix,
  Boolean,
  Date,
  Date_time,
  Time
from {{ ref('src/Integrations/Google_sheets_all_field_types/Copy of Numeric2-Sheet1') }}
